<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" ignored="0" total="5" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="36136" started-at="2019-08-03T11:24:45Z" finished-at="2019-08-03T11:25:21Z">
    <groups>
      <group name="smoke">
        <method signature="SearchTest.textSearch_Test()[pri:0, instance:com.r1rcm.tests.SearchTest@1593948d]" name="textSearch_Test" class="com.r1rcm.tests.SearchTest"/>
      </group> <!-- smoke -->
    </groups>
    <test name="Default test" duration-ms="36136" started-at="2019-08-03T11:24:45Z" finished-at="2019-08-03T11:25:21Z">
      <class name="com.r1rcm.tests.SearchTest">
        <test-method status="PASS" signature="makeDBConnection()[pri:0, instance:com.r1rcm.tests.SearchTest@1593948d]" name="makeDBConnection" is-config="true" duration-ms="11" started-at="2019-08-03T16:54:45Z" finished-at="2019-08-03T16:54:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- makeDBConnection -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.r1rcm.tests.SearchTest@1593948d]" name="setUp" is-config="true" duration-ms="19949" started-at="2019-08-03T16:54:45Z" finished-at="2019-08-03T16:55:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="failTest()[pri:0, instance:com.r1rcm.tests.SearchTest@1593948d]" name="failTest" duration-ms="25" started-at="2019-08-03T16:55:05Z" finished-at="2019-08-03T16:55:05Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at org.testng.Assert.assertTrue(Assert.java:51)
	at com.r1rcm.tests.SearchTest.failTest(SearchTest.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failTest -->
        <test-method status="PASS" signature="testReports()[pri:0, instance:com.r1rcm.tests.SearchTest@1593948d]" name="testReports" duration-ms="2" started-at="2019-08-03T16:55:05Z" finished-at="2019-08-03T16:55:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testReports -->
        <test-method status="PASS" signature="textSearch_Test()[pri:0, instance:com.r1rcm.tests.SearchTest@1593948d]" name="textSearch_Test" duration-ms="5762" started-at="2019-08-03T16:55:05Z" finished-at="2019-08-03T16:55:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- textSearch_Test -->
        <test-method status="SKIP" signature="skipTest()[pri:0, instance:com.r1rcm.tests.SearchTest@1593948d]" name="skipTest" duration-ms="4" started-at="2019-08-03T16:55:11Z" finished-at="2019-08-03T16:55:11Z">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping - This is not ready for testing ]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping - This is not ready for testing 
	at com.r1rcm.tests.SearchTest.skipTest(SearchTest.java:91)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- skipTest -->
        <test-method status="PASS" signature="navigationToAgileTest()[pri:0, instance:com.r1rcm.tests.SearchTest@1593948d]" name="navigationToAgileTest" duration-ms="8602" started-at="2019-08-03T16:55:11Z" depends-on-methods="com.r1rcm.tests.SearchTest.textSearch_Test" finished-at="2019-08-03T16:55:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- navigationToAgileTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.r1rcm.tests.SearchTest@1593948d]" name="tearDown" is-config="true" duration-ms="1753" started-at="2019-08-03T16:55:20Z" finished-at="2019-08-03T16:55:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="closeDBConnection()[pri:0, instance:com.r1rcm.tests.SearchTest@1593948d]" name="closeDBConnection" is-config="true" duration-ms="1" started-at="2019-08-03T16:55:21Z" finished-at="2019-08-03T16:55:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeDBConnection -->
      </class> <!-- com.r1rcm.tests.SearchTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
